### PR TITLE
C# Exec Stager

### PR DESCRIPTION
**Pull request by bufferov3rride**
C# Executable Stager. 
Bypass AMSI using The Patching Technique then executing the payload and hiding the window.

### CODE REVIEW

**Comment by b2az** [comment]
Hi @bufferov3rride ,

For future usage it would make sense replacing/adding the b64-blob in `STStager.generate`.
If something changes within the core, all stagers have to be updated.
This affects also:

- Server/stagers/templates/wmic.xsl

- Server/stagers/templates/msbuild.xml

How should we proceed here guys? (@bufferov3rride & @byt3bl33d3r )

**Comment by byt3bl33d3r** [comment]
@bufferov3rride i appreciate the effort and I definitely think this would be a great addition, but I'm having a hard time understanding why the AMSI bypass is needed here. it's a C# stager, so we don't have to worry about any of the PowerShell protections. Am i missing something?

**Comment by bufferov3rride** [comment]
@byt3bl33d3r hey, basically people want to load ps modules right? stuff like powerview etc..
now at the moment you have a powershell option which adds a system.management.automation reference and that way you can Invoke PS. the problem is AMSI hooks into system.management.automation,cmd,powershell,vbs etc.. so unless you bypass it the latest versions of windows will block it. the current bypass implemented in powershell.py is not enough to bypass the latest win defender simply because MS has changed it so it doesnt scan for strings anymore using ScanString func it uses a new function called ScanBuffer.
i hope it makes sense

**Comment by fsacer** [comment]
maybe AmsiEnable registry key would help here hmm

**Comment by byt3bl33d3r** [comment]
Closing since this is based off the old version. I'll be adding a module like this today.

**Pull request closed without merging**
