### PR TITLE
Adding Rubeus support for Kerberos-related attacks

### PR DESCRIPTION
**Pull request by maaaaz**
Hello @byt3bl33d3r,

SILENTTRINITY is already awesome, but it will even be awesomer with the [GhostPack tools](https://github.com/GhostPack/) integrated inside :-)

I'm starting here with `Rubeus` (that I [compiled myself](https://github.com/maaaaz/GhostPack-compiled)) but if you like the idea, I'll also do it for the other tools (`SharpUp` etc.).

An output example from this module:
```
ST (modules)(ipy/rubeus) ≫ options                                                                                                                            
+-------------+----------+------------+-----------------------------------------------------+
| Option Name | Required | Value      | Description                                         |
+-------------+----------+------------+-----------------------------------------------------+
| Command     | True     | kerberoast | The Rubeus command to use (by default "kerberoast") |
+-------------+----------+------------+-----------------------------------------------------+


ST (modules)(ipy/rubeus) ≫ run 311b43d4-59a7-42bb-b571-7b64c8393702                                                                                           
[+] 311b43d4-59a7-42bb-b571-7b64c8393702 returned job result (id: lSueRgJI)

   ______        _                      
  (_____ \      | |                     
   _____) )_   _| |__  _____ _   _  ___ 
  |  __  /| | | |  _ \| ___ | | | |/___)
  | |  \ \| |_| | |_) ) ____| |_| |___ |
  |_|   |_|____/|____/|_____)____/(___/

  v1.4.2 


[*] Action: Kerberoasting

[*] NOTICE: AES hashes will be returned for AES-enabled accounts.
[*]         Use /ticket:X or /tgtdeleg to force RC4_HMAC for these accounts.

[*] Searching the current domain for Kerberoastable users

[*] Found 1 user(s) to Kerberoast!

[*] SamAccountName         : kerbgrill
[*] DistinguishedName      : CN=kerbgrill,CN=Users,DC=ADYOLO,DC=SWAG
[*] ServicePrincipalName   : DC1/kerbgrill.adyolo.swag:80
[*] Supported ETypes       : RC4_HMAC_DEFAULT
[*] Hash                   : $krb5tgs$23$*kerbgrill$ADYOLO.SWAG$DC1/kerbgrill.adyolo.swag:80*$ADB7266D4FECA22
                             7426809A8993A10FD$8437FA475BAADAC6E95308C7B6F818907BE4[...]
```

Cheers !

Thomas.

### CODE REVIEW

**Comment by byt3bl33d3r** [comment]
Hey @maaaaz ! thanks for the PR but I think i'm going to be moving away from having modules that contain embedded binaries, it's too much work to keep updating them unfortunately. At the end of the day this is exactly what the `execute-assembly` module is for :) 

Cheers

**Comment by maaaaz** [comment]
Hi @byt3bl33d3r, 
You're right, I was also thinking the same thing but I really realized that I would be too lazy to specify each time which binary to use which `execute-assembly`, so I would prefer to have every GhostPack tool already setup and ready to be launched in a standalone module :-)

**Comment by byt3bl33d3r** [comment]
good idea, or we could include these modules but as long as everyone has an understanding that if they want the binary updated they have to do it themselves

**Comment by maaaaz** [comment]
Yep.
I can prepare the PR for the other GhostPack binaries if you want !

**Comment by byt3bl33d3r** [comment]
I'd put that on hold for now, i'll give this some thought and get back to you. The alias approach seems a lot cleaner tbh.

**Pull request closed without merging**
