### PR TITLE
Feature/results processing

### PR DESCRIPTION
**Pull request by davidtavarez**
I think the `Module` could manage the response in order to create more powerful tools. This is a `Work In Progress` PR until we discuss this feature.

```

   _____ ______    _______   __________________  _____   ______________  __
  / ___//  _/ /   / ____/ | / /_  __/_  __/ __ \/  _/ | / /  _/_  __/\ \/ /
  \__ \ / // /   / __/ /  |/ / / /   / / / /_/ // //  |/ // /  / /    \  /
 ___/ // // /___/ /___/ /|  / / /   / / / _, _// // /|  // /  / /     / /
/____/___/_____/_____/_/ |_/ /_/   /_/ /_/ |_/___/_/ |_/___/ /_/     /_/

                         Codename: Ánima
                         Version: 0.0.1dev

ST ≫ listeners                                                                                                                                                                  
ST (listeners) ≫ use http                                                                                                                                                       
ST (listeners)(http) ≫ set BindIP 10.0.0.3                                                                                                                                      
ST (listeners)(http) ≫ set Port 8090                                                                                                                                            
ST (listeners)(http) ≫ start                                                                                                                                                    
[+] Listener 'http' started successfully!
ST (listeners)(http) ≫ modules                                                                                                                                                  
ST (modules) ≫                                                                                                                                                                  
ST (modules) ≫ use shell                                                                                                                                                        
ST (modules)(shell) ≫ set Command whoami                                                                                                                                        
ST (modules)(shell) ≫ Running on https://10.0.0.3:8090 (CTRL + C to quit)                                                                                                       
[*] Re-attaching orphaned session from 10.0.0.6 ...
[+] New session b40d1046-2039-4322-91a7-8940302606e3 connected! (10.0.0.6)
ST (modules)(shell) ≫ run all                                                                                                                                                                                                                                                                                                           
[+] b40d1046-2039-4322-91a7-8940302606e3 returned job result (id: xfFnkmaH)
﻿[*] Path: C:\WINDOWS\System32\ Command: whoami Args: 
desktop-au143ed\hacklab

```

### CODE REVIEW

**Comment by Jb05s** [comment]
For the 'downloader' module, I can't seem to pull any files from the remote system after a certain file size is reached. Relatively small .txt files work perfectly fine.. but when a file reaches about.. say 10,000kb.. the file either doesn't get pulled (after waiting quite some time) or the file gets partially pulled, but the file content always contains 77kb and looks to be encrypted? Have any of you experienced this while testing?

**Comment by davidtavarez** [comment]
I'm trying to find a workaround @Jb05s

**Comment by byt3bl33d3r** [comment]
@davidtavarez Just an update on this, implementing crypto in the comms channel required refactoring the entire way jobs and sessions are handled. Once I finish this up we can work on implementing this in the new code base

**Comment by b2az** [comment]
@davidtavarez are there any further informations to this topic?
In some cases, it's better to process the data on the server instead of doing it on the client.
Would be interesting for me, because atm i'm working on new modules.

Best,
b2az

**Comment by davidtavarez** [comment]
Hey @b2az what's happening is @byt3bl33d3r is refactoring the way jobs and sessions are handled ([comment here](https://github.com/byt3bl33d3r/SILENTTRINITY/pull/15#issuecomment-433450720)). So, I'm just waiting until the refactoring is done and stable to continue working on this PR. I want to achieve a more interactive interaction between server an clients. I decided to not place more PRs until the refactoring is done, after that I will continue contributing to this repo.

**Pull request closed without merging**
